# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gui_Predictor(object):
    def setupUi(self, Gui_Predictor):
        Gui_Predictor.setObjectName("Gui_Predictor")
        Gui_Predictor.resize(1095, 690)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        Gui_Predictor.setPalette(palette)
        Gui_Predictor.setAutoFillBackground(False)
        Gui_Predictor.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Gui_Predictor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QWidget {\n"
"    background-color: #f0f0f0;\n"
"    font-family: Arial, sans-serif;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #333333;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit, QComboBox {\n"
"    background-color: white;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"    text-transform: uppercase\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #cccccc;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #e0e0e0;\n"
"    color: #333333;\n"
"    padding: 5px;\n"
"    border: 1px solid #cccccc;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"    margin-top: 1ex;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 3px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(460, 0, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(7)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font: 63 italic 14pt \"Segoe UI Semibold\";")
        self.label_8.setObjectName("label_8")
        self.groupBoxParametros = QtWidgets.QGroupBox(self.frame)
        self.groupBoxParametros.setGeometry(QtCore.QRect(20, 30, 761, 241))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxParametros.setFont(font)
        self.groupBoxParametros.setObjectName("groupBoxParametros")
        self.lineVecinos = QtWidgets.QLineEdit(self.groupBoxParametros)
        self.lineVecinos.setGeometry(QtCore.QRect(219, 71, 81, 29))
        self.lineVecinos.setAlignment(QtCore.Qt.AlignCenter)
        self.lineVecinos.setObjectName("lineVecinos")
        self.comboBoxRuleta = QtWidgets.QComboBox(self.groupBoxParametros)
        self.comboBoxRuleta.setGeometry(QtCore.QRect(219, 36, 181, 28))
        self.comboBoxRuleta.setObjectName("comboBoxRuleta")
        self.lineProbabiliada = QtWidgets.QLineEdit(self.groupBoxParametros)
        self.lineProbabiliada.setGeometry(QtCore.QRect(219, 143, 81, 29))
        self.lineProbabiliada.setAlignment(QtCore.Qt.AlignCenter)
        self.lineProbabiliada.setObjectName("lineProbabiliada")
        self.lineTardanza = QtWidgets.QLineEdit(self.groupBoxParametros)
        self.lineTardanza.setGeometry(QtCore.QRect(219, 107, 81, 29))
        self.lineTardanza.setAlignment(QtCore.Qt.AlignCenter)
        self.lineTardanza.setObjectName("lineTardanza")
        self.widget = QtWidgets.QWidget(self.groupBoxParametros)
        self.widget.setGeometry(QtCore.QRect(70, 40, 143, 141))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.widget1 = QtWidgets.QWidget(self.groupBoxParametros)
        self.widget1.setGeometry(QtCore.QRect(220, 190, 197, 34))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnIniciar = QtWidgets.QPushButton(self.widget1)
        self.btnIniciar.setObjectName("btnIniciar")
        self.horizontalLayout.addWidget(self.btnIniciar)
        self.btnReiniciar = QtWidgets.QPushButton(self.widget1)
        self.btnReiniciar.setEnabled(False)
        self.btnReiniciar.setObjectName("btnReiniciar")
        self.horizontalLayout.addWidget(self.btnReiniciar)
        self.splitter = QtWidgets.QSplitter(self.groupBoxParametros)
        self.splitter.setGeometry(QtCore.QRect(310, 80, 200, 91))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_6 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.groupBoxJuego = QtWidgets.QGroupBox(self.frame)
        self.groupBoxJuego.setGeometry(QtCore.QRect(20, 260, 1061, 391))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxJuego.setFont(font)
        self.groupBoxJuego.setObjectName("groupBoxJuego")
        self.lineIngresoNumero = QtWidgets.QLineEdit(self.groupBoxJuego)
        self.lineIngresoNumero.setGeometry(QtCore.QRect(82, 30, 101, 32))
        self.lineIngresoNumero.setObjectName("lineIngresoNumero")
        self.btnPredecir = QtWidgets.QPushButton(self.groupBoxJuego)
        self.btnPredecir.setGeometry(QtCore.QRect(190, 30, 103, 32))
        self.btnPredecir.setObjectName("btnPredecir")
        self.btnBorrar = QtWidgets.QPushButton(self.groupBoxJuego)
        self.btnBorrar.setGeometry(QtCore.QRect(300, 30, 92, 32))
        self.btnBorrar.setObjectName("btnBorrar")
        self.listResultados = QtWidgets.QListView(self.groupBoxJuego)
        self.listResultados.setGeometry(QtCore.QRect(80, 110, 551, 271))
        self.listResultados.setObjectName("listResultados")
        self.label_7 = QtWidgets.QLabel(self.groupBoxJuego)
        self.label_7.setGeometry(QtCore.QRect(340, 90, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tableProbabilidad = QtWidgets.QTableView(self.groupBoxJuego)
        self.tableProbabilidad.setGeometry(QtCore.QRect(640, 110, 401, 271))
        self.tableProbabilidad.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableProbabilidad.setObjectName("tableProbabilidad")
        self.label_9 = QtWidgets.QLabel(self.groupBoxJuego)
        self.label_9.setGeometry(QtCore.QRect(780, 90, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btnGuardar = QtWidgets.QPushButton(self.groupBoxJuego)
        self.btnGuardar.setGeometry(QtCore.QRect(400, 30, 111, 32))
        self.btnGuardar.setObjectName("btnGuardar")
        self.tableNrosSalidos = QtWidgets.QTableWidget(self.groupBoxJuego)
        self.tableNrosSalidos.setGeometry(QtCore.QRect(10, 110, 61, 261))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setKerning(True)
        self.tableNrosSalidos.setFont(font)
        self.tableNrosSalidos.setStyleSheet("QHeaderView::section {\n"
"    background-color: black;\n"
"    color: white;\n"
"    padding: 3px 8px;\n"
"    border: 1px solid #444;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.tableNrosSalidos.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableNrosSalidos.setObjectName("tableNrosSalidos")
        self.tableNrosSalidos.setColumnCount(1)
        self.tableNrosSalidos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableNrosSalidos.setHorizontalHeaderItem(0, item)
        self.tableNrosSalidos.horizontalHeader().setDefaultSectionSize(60)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(790, 30, 271, 231))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableEstadistica = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableEstadistica.setGeometry(QtCore.QRect(30, 40, 201, 161))
        self.tableEstadistica.setStyleSheet("QHeaderView::section {\n"
"    background-color: black;\n"
"    color: white;\n"
"    padding: 3px 8px;\n"
"    border: 1px solid #444;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    width: 100%;\n"
"    height: 100%;\n"
"    margin: 0;\n"
"    padding: 0;\n"
"}\n"
"\n"
"/* Estilo para el encabezado vertical */\n"
"QTableWidget::verticalHeader::section {\n"
"    background-color: black;\n"
"    color: white;\n"
"    padding: 3px 8px;\n"
"    border: 1px solid #444;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"/* Estilo para la esquina superior izquierda */\n"
"QTableCornerButton::section {\n"
"    background-color: black;\n"
"    border: 1px solid #444;\n"
"}\n"
"")
        self.tableEstadistica.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableEstadistica.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableEstadistica.setShowGrid(True)
        self.tableEstadistica.setObjectName("tableEstadistica")
        self.tableEstadistica.setColumnCount(1)
        self.tableEstadistica.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadistica.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadistica.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadistica.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadistica.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEstadistica.setHorizontalHeaderItem(0, item)
        self.tableEstadistica.horizontalHeader().setVisible(True)
        self.tableEstadistica.horizontalHeader().setStretchLastSection(False)
        self.tableEstadistica.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.frame)
        Gui_Predictor.setCentralWidget(self.centralwidget)

        self.retranslateUi(Gui_Predictor)
        QtCore.QMetaObject.connectSlotsByName(Gui_Predictor)

    def retranslateUi(self, Gui_Predictor):
        _translate = QtCore.QCoreApplication.translate
        Gui_Predictor.setWindowTitle(_translate("Gui_Predictor", "Predictor"))
        self.label_8.setText(_translate("Gui_Predictor", "Predictor de Ruleta"))
        self.groupBoxParametros.setTitle(_translate("Gui_Predictor", "Parametros"))
        self.lineVecinos.setText(_translate("Gui_Predictor", "3"))
        self.lineProbabiliada.setText(_translate("Gui_Predictor", "20"))
        self.lineTardanza.setText(_translate("Gui_Predictor", "5"))
        self.label.setText(_translate("Gui_Predictor", "Ruleta:"))
        self.label_2.setText(_translate("Gui_Predictor", "Cantidad de vecinos:"))
        self.label_3.setText(_translate("Gui_Predictor", "Limite de Tardanza:"))
        self.label_4.setText(_translate("Gui_Predictor", "Umbral de Probabilidad:"))
        self.btnIniciar.setText(_translate("Gui_Predictor", "Iniciar "))
        self.btnReiniciar.setText(_translate("Gui_Predictor", "Reiniciar"))
        self.label_6.setText(_translate("Gui_Predictor", "Valores entre (1-4) (0 = sin vecinos)"))
        self.label_10.setText(_translate("Gui_Predictor", "Valores entre (1 al 5)"))
        self.label_11.setText(_translate("Gui_Predictor", "Valores entre (10-100)"))
        self.groupBoxJuego.setTitle(_translate("Gui_Predictor", "Juego"))
        self.btnPredecir.setText(_translate("Gui_Predictor", "Predecir"))
        self.btnBorrar.setText(_translate("Gui_Predictor", "Borrar"))
        self.label_7.setText(_translate("Gui_Predictor", "Resultados"))
        self.label_9.setText(_translate("Gui_Predictor", "Probabilidades"))
        self.btnGuardar.setText(_translate("Gui_Predictor", "Guardar "))
        item = self.tableNrosSalidos.horizontalHeaderItem(0)
        item.setText(_translate("Gui_Predictor", "NRO"))
        self.groupBox_2.setTitle(_translate("Gui_Predictor", "Estadistica de Juego"))
        item = self.tableEstadistica.verticalHeaderItem(0)
        item.setText(_translate("Gui_Predictor", "Ingresados"))
        item = self.tableEstadistica.verticalHeaderItem(1)
        item.setText(_translate("Gui_Predictor", "Predecidos"))
        item = self.tableEstadistica.verticalHeaderItem(2)
        item.setText(_translate("Gui_Predictor", "Aciertos"))
        item = self.tableEstadistica.verticalHeaderItem(3)
        item.setText(_translate("Gui_Predictor", "No acertados"))
        item = self.tableEstadistica.horizontalHeaderItem(0)
        item.setText(_translate("Gui_Predictor", "Cantidad"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gui_Predictor = QtWidgets.QMainWindow()
    ui = Ui_Gui_Predictor()
    ui.setupUi(Gui_Predictor)
    Gui_Predictor.show()
    sys.exit(app.exec_())
