# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# pyright: reportAttributeAccessIssue=false

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gui_Predictor(object):
    def setupUi(self, Gui_Predictor):
        Gui_Predictor.setObjectName("Gui_Predictor")
        Gui_Predictor.resize(1097, 888)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 229, 229))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 102, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        Gui_Predictor.setPalette(palette)
        Gui_Predictor.setAutoFillBackground(False)
        Gui_Predictor.setStyleSheet("QWidget {\n"
                                    "    background-color: #f0f0f0;\n"
                                    "    font-family: Arial, sans-serif;\n"
                                    "}\n"
                                    "\n"
                                    "QLabel {\n"
                                    "    color: #333333;\n"
                                    "    font-size: 14px;\n"
                                    "}\n"
                                    "\n"
                                    "QLineEdit, QComboBox {\n"
                                    "    background-color: white;\n"
                                    "    border: 1px solid #cccccc;\n"
                                    "    border-radius: 4px;\n"
                                    "    padding: 5px;\n"
                                    "    font-size: 14px;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton {\n"
                                    "    background-color: #4CAF50;\n"
                                    "    color: white;\n"
                                    "    border: none;\n"
                                    "    padding: 8px 16px;\n"
                                    "    font-size: 14px;\n"
                                    "    border-radius: 4px;\n"
                                    "    font-weight: bold;\n"
                                    "    text-transform: uppercase\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover {\n"
                                    "    background-color: #45a049;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed {\n"
                                    "    background-color: #3e8e41;\n"
                                    "}\n"
                                    "\n"
                                    "QTableWidget {\n"
                                    "    background-color: white;\n"
                                    "    border: 1px solid #cccccc;\n"
                                    "}\n"
                                    "\n"
                                    "QTableWidget::item {\n"
                                    "    padding: 5px;\n"
                                    "}\n"
                                    "\n"
                                    "QHeaderView::section {\n"
                                    "    background-color: #e0e0e0;\n"
                                    "    color: #333333;\n"
                                    "    padding: 5px;\n"
                                    "    border: 1px solid #cccccc;\n"
                                    "    font-weight: bold;\n"
                                    "}\n"
                                    "\n"
                                    "QGroupBox {\n"
                                    "    border: 1px solid #cccccc;\n"
                                    "    border-radius: 4px;\n"
                                    "    margin-top: 1ex;\n"
                                    "    font-size: 14px;\n"
                                    "    font-weight: bold;\n"
                                    "}\n"
                                    "\n"
                                    "QGroupBox::title {\n"
                                    "    subcontrol-origin: margin;\n"
                                    "    subcontrol-position: top left;\n"
                                    "    padding: 0 3px;\n"
                                    "    color: #333333;\n"
                                    "}\n"
                                    "\n"
                                    "QTextEdit {\n"
                                    "    background-color: white;\n"
                                    "    border: 1px solid #cccccc;\n"
                                    "    border-radius: 4px;\n"
                                    "}")
        self.centralwidget = QtWidgets.QWidget(Gui_Predictor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(470, 10, 201, 51))
        self.label_8.setStyleSheet("font: 63 italic 14pt \"Segoe UI Semibold\";")
        self.label_8.setObjectName("label_8")
        self.groupBoxParametros = QtWidgets.QGroupBox(self.frame)
        self.groupBoxParametros.setGeometry(QtCore.QRect(20, 60, 621, 252))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxParametros.setFont(font)
        self.groupBoxParametros.setObjectName("groupBoxParametros")
        self.btnReiniciar = QtWidgets.QPushButton(self.groupBoxParametros)
        self.btnReiniciar.setGeometry(QtCore.QRect(340, 180, 121, 51))
        self.btnReiniciar.setObjectName("btnReiniciar")
        self.btnIniciar = QtWidgets.QPushButton(self.groupBoxParametros)
        self.btnIniciar.setGeometry(QtCore.QRect(220, 180, 111, 51))
        self.btnIniciar.setObjectName("btnIniciar")
        self.lineVecinos = QtWidgets.QLineEdit(self.groupBoxParametros)
        self.lineVecinos.setGeometry(QtCore.QRect(219, 71, 81, 29))
        self.lineVecinos.setObjectName("lineVecinos")
        self.label_3 = QtWidgets.QLabel(self.groupBoxParametros)
        self.label_3.setGeometry(QtCore.QRect(13, 107, 158, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBoxParametros)
        self.label_2.setGeometry(QtCore.QRect(13, 71, 166, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBoxParametros)
        self.label.setGeometry(QtCore.QRect(13, 36, 56, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBoxRuleta = QtWidgets.QComboBox(self.groupBoxParametros)
        self.comboBoxRuleta.setGeometry(QtCore.QRect(219, 36, 271, 28))
        self.comboBoxRuleta.setObjectName("comboBoxRuleta")
        self.lineProbabiliada = QtWidgets.QLineEdit(self.groupBoxParametros)
        self.lineProbabiliada.setGeometry(QtCore.QRect(219, 143, 81, 29))
        self.lineProbabiliada.setObjectName("lineProbabiliada")
        self.lineTardanza = QtWidgets.QLineEdit(self.groupBoxParametros)
        self.lineTardanza.setGeometry(QtCore.QRect(219, 107, 81, 29))
        self.lineTardanza.setObjectName("lineTardanza")
        self.label_4 = QtWidgets.QLabel(self.groupBoxParametros)
        self.label_4.setGeometry(QtCore.QRect(13, 143, 199, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBoxJuego = QtWidgets.QGroupBox(self.frame)
        self.groupBoxJuego.setGeometry(QtCore.QRect(10, 330, 1061, 541))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxJuego.setFont(font)
        self.groupBoxJuego.setObjectName("groupBoxJuego")
        self.lineIngresoNumero = QtWidgets.QLineEdit(self.groupBoxJuego)
        self.lineIngresoNumero.setGeometry(QtCore.QRect(524, 22, 101, 32))
        self.lineIngresoNumero.setObjectName("lineIngresoNumero")
        self.btnPredecir = QtWidgets.QPushButton(self.groupBoxJuego)
        self.btnPredecir.setGeometry(QtCore.QRect(632, 22, 103, 32))
        self.btnPredecir.setObjectName("btnPredecir")
        self.btnBorrar = QtWidgets.QPushButton(self.groupBoxJuego)
        self.btnBorrar.setGeometry(QtCore.QRect(742, 22, 92, 32))
        self.btnBorrar.setObjectName("btnBorrar")
        self.btnGuardar = QtWidgets.QPushButton(self.groupBoxJuego)
        self.btnGuardar.setGeometry(QtCore.QRect(841, 22, 177, 32))
        self.btnGuardar.setObjectName("btnGuardar")
        self.label_5 = QtWidgets.QLabel(self.groupBoxJuego)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_Numeros_salidos = QtWidgets.QLabel(self.groupBoxJuego)
        self.label_Numeros_salidos.setGeometry(QtCore.QRect(30, 50, 91, 16))
        self.label_Numeros_salidos.setObjectName("label_Numeros_salidos")
        self.listResultados = QtWidgets.QListView(self.groupBoxJuego)
        self.listResultados.setGeometry(QtCore.QRect(30, 170, 551, 361))
        self.listResultados.setObjectName("listResultados")
        self.label_7 = QtWidgets.QLabel(self.groupBoxJuego)
        self.label_7.setGeometry(QtCore.QRect(250, 150, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tableProbabilidad = QtWidgets.QTableView(self.groupBoxJuego)
        self.tableProbabilidad.setGeometry(QtCore.QRect(600, 170, 431, 361))
        self.tableProbabilidad.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableProbabilidad.setObjectName("tableProbabilidad")
        self.label_9 = QtWidgets.QLabel(self.groupBoxJuego)
        self.label_9.setGeometry(QtCore.QRect(780, 150, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(680, 60, 311, 252))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(30, 40, 251, 191))
        self.tableWidget_2.setStyleSheet("QHeaderView::section {\n"
                                         "    background-color: black;\n"
                                         "    color: white;\n"
                                         "    padding: 3px 8px;\n"
                                         "    border: 1px solid #444;\n"
                                         "    font-weight: bold;\n"
                                         "    text-align: center;\n"
                                         "    qproperty-alignment: AlignCenter;\n"
                                         "}\n"
                                         "\n"
                                         "QTableWidget {\n"
                                         "    width: 100%;\n"
                                         "    height: 100%;\n"
                                         "    margin: 0;\n"
                                         "    padding: 0;\n"
                                         "}\n"
                                         "\n"
                                         "/* Estilo para el encabezado vertical */\n"
                                         "QTableWidget::verticalHeader::section {\n"
                                         "    background-color: black;\n"
                                         "    color: white;\n"
                                         "    padding: 3px 8px;\n"
                                         "    border: 1px solid #444;\n"
                                         "    font-weight: bold;\n"
                                         "    text-align: center;\n"
                                         "    qproperty-alignment: AlignCenter;\n"
                                         "}\n"
                                         "\n"
                                         "/* Estilo para la esquina superior izquierda */\n"
                                         "QTableCornerButton::section {\n"
                                         "    background-color: black;\n"
                                         "    border: 1px solid #444;\n"
                                         "}\n"
                                         "")
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.frame)
        Gui_Predictor.setCentralWidget(self.centralwidget)

        self.retranslateUi(Gui_Predictor)
        QtCore.QMetaObject.connectSlotsByName(Gui_Predictor)

    def retranslateUi(self, Gui_Predictor):
        _translate = QtCore.QCoreApplication.translate
        Gui_Predictor.setWindowTitle(_translate("Gui_Predictor", "Predictor"))
        self.label_8.setText(_translate("Gui_Predictor", "Predictor de Ruleta"))
        self.groupBoxParametros.setTitle(_translate("Gui_Predictor", "Parametros"))
        self.btnReiniciar.setText(_translate("Gui_Predictor", "Reiniciar"))
        self.btnIniciar.setText(_translate("Gui_Predictor", "Iniciar "))
        self.label_3.setText(_translate("Gui_Predictor", "Limite de Tardanza:"))
        self.label_2.setText(_translate("Gui_Predictor", "Cantidad de vecinos:"))
        self.label.setText(_translate("Gui_Predictor", "Ruleta:"))
        self.label_4.setText(_translate("Gui_Predictor", "Umbral de Probabilidad:"))
        self.groupBoxJuego.setTitle(_translate("Gui_Predictor", "Juego"))
        self.btnPredecir.setText(_translate("Gui_Predictor", "Predecir"))
        self.btnBorrar.setText(_translate("Gui_Predictor", "Borrar"))
        self.btnGuardar.setText(_translate("Gui_Predictor", "Guardar Numeros"))
        self.label_5.setText(_translate("Gui_Predictor", "Numeros salidos"))
        self.label_Numeros_salidos.setText(_translate("Gui_Predictor", "1.2.3.4.5.6"))
        self.label_7.setText(_translate("Gui_Predictor", "Resultados"))
        self.label_9.setText(_translate("Gui_Predictor", "Probabilidades"))
        self.groupBox_2.setTitle(_translate("Gui_Predictor", "Estadistica de Juego"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Gui_Predictor", "Ingresados"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Gui_Predictor", "Predecidos"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Gui_Predictor", "Aciertos"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Gui_Predictor", "No acertados"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Gui_Predictor", "Cantidad"))



